#! /bin/sh

# autostart
~/.config/polybar/launch.sh &
feh --bg-fill /mnt/data/zold/img/bg/onedark1.png &
flameshot &
numlockx &
xsetroot -cursor_name left_ptr &
pgrep -x picom > /dev/null || picom &

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# bspc config
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width       2
bspc config window_gap         12
bspc config split_ratio        0.5
bspc config top_padding        35
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc config normal_border_color  '#444b6a'
bspc config active_border_color  '#ad8ee6'
bspc config focused_border_color '#f7768e'
bspc config urgent_border_color  '#9ece6a'

bspc rule -a Emacs state=tiled
