#! /bin/sh


# autostart
feh --bg-fill /mnt/data/img/bg/onedark1.png &
$HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
flameshot &

# cursor and numpad fix
xsetroot -cursor_name left_ptr
numlockx &

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# configuration
bspc config border_width       2
bspc config window_gap         16
bspc config top_padding        56
bspc config split_ratio        0.5
bspc config borderless_monocle true
bspc config gapless_monocle    true

# colors
bspc config normal_border_color   '#242d35'
bspc config active_border_color   '#94cf95'
bspc config focused_border_color  '#fb6396'
bspc config presel_feedback_color '#242d35'
bspc config urgent_border_color   '#fb7863'

